name: Generar Tokens con Style Dictionary

on:
  push:
    branches:
      - develop
    paths:
      - 'config.json'
      - 'tokens/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Lista de archivos en la raíz después del checkout
        run: ls -al

      - name: Verificar existencia de config.json
        run: test -f config.json && echo "config.json existe" || echo "config.json no existe"

      - name: Mostrar contenido de config.json
        run: cat config.json

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install style-dictionary

      - name: Ejecutar Style Dictionary
        run: npx style-dictionary build config.json

      - name: Subir cambios generados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizar tokens generados con Style Dictionary"
          branch: develop
          file_pattern: "build/**"
