name: Generar Tokens con Style Dictionary

on:
  push:
    branches:
      - develop
    paths:
      - 'DesignSystem/config.json'
      - 'DesignSystem/tokens/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Lista de archivos en la raíz después del checkout
        run: ls -al

      - name: Lista de archivos en el directorio DesignSystem
        run: ls -al DesignSystem

      - name: Verificar existencia de config.json en DesignSystem
        run: test -f DesignSystem/config.json && echo "DesignSystem/config.json existe" || echo "DesignSystem/config.json no existe"

      - name: Mostrar contenido de DesignSystem/config.json
        run: cat DesignSystem/config.json

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install style-dictionary

      - name: Cambiar al directorio DesignSystem
        working-directory: DesignSystem
        run: pwd

      - name: Ejecutar Style Dictionary
        working-directory: DesignSystem
        run: npx style-dictionary build config.json

      - name: Lista de archivos generados en DesignSystem
        run: ls -al DesignSystem

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Commit de cambios generados
        run: |
          git add DesignSystem/**
          git commit -m "Commit de cambios generados antes de auto-commit" || echo "No hay cambios para commitear"

      - name: Subir cambios generados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizar tokens generados con Style Dictionary"
          branch: develop
          file_pattern: "DesignSystem/**"
