name: Generar Tokens con Style Dictionary

on:
  push:
    branches:
      - develop # Ejecutar solo en develop
    paths:
      - 'DesignSystem/config.json'
      - 'DesignSystem/tokens/**'
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Lista de archivos en Sources
        run: ls -al DesignSystem/Sources/

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install style-dictionary

      - name: Ejecutar Style Dictionary
        run: npx style-dictionary build DesignSystem/Sources/config.js

      - name: Subir cambios generados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizar tokens generados con Style Dictionary"
          branch: develop # commit en la rama develop
          file_pattern: "build/**"
