name: Generar Tokens con Style Dictionary

on:
  push:
    branches:
      - develop
    paths:
      - 'DesignSystem/build.js'
      - 'DesignSystem/ComplexTokens/**'
  workflow_dispatch:

permissions:
  contents: write  # Permiso para escribir contenido en el repositorio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Lista de archivos en la raíz después del checkout
        run: ls -al

      - name: Lista de archivos en el directorio DesignSystem
        run: ls -al DesignSystem

      - name: Verificar existencia de build.js en DesignSystem
        run: test -f DesignSystem/build.js && echo "DesignSystem/build.js existe" || echo "DesignSystem/build.js no existe"

      - name: Mostrar contenido de DesignSystem/build.js
        run: cat DesignSystem/build.js

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install style-dictionary

      - name: Cambiar al directorio DesignSystem
        working-directory: DesignSystem
        run: pwd

      - name: Ejecutar Style Dictionary
        working-directory: DesignSystem
        run: npx style-dictionary build -c build.js

      - name: Lista de archivos generados en DesignSystem
        run: ls -al DesignSystem

      - name: Añadir cambios generados
        run: git add DesignSystem/**

      - name: Subir cambios generados
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        with:
          commit_message: "Actualizar tokens generados con Style Dictionary"
          branch: develop
          file_pattern: "DesignSystem/**"
