// Generated by Style Dictionary on 2025-03-14T15:46:36.246Z
import UIKit

public struct BoxShadow {
  let color: UIColor
  let offsetX: CGFloat
  let offsetY: CGFloat
  let blurRadius: CGFloat
  let spread: CGFloat
  let type: String? = nil
}

public struct StyleDictionaryBoxShadow {
  public static let bui_global_datepicker_calendar_container_default = BoxShadow(offsetX: CGFloat(0), offsetY: CGFloat(0), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let bui_global_dialog_container_default = BoxShadow(offsetX: CGFloat(0), offsetY: CGFloat(0), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let bui_global_tooltip_default = BoxShadow(offsetX: CGFloat(0), offsetY: CGFloat(0), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let bui_global_main_header_default = BoxShadow(offsetX: CGFloat(0), offsetY: CGFloat(4), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let bui_global_dropdown_option_list_default = BoxShadow(offsetX: CGFloat(0), offsetY: CGFloat(0), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let bui_global_toast_default = BoxShadow(offsetX: CGFloat(0), offsetY: CGFloat(0), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let bui_global_carousel_single_arrow_control_container_default = BoxShadow(offsetX: CGFloat(0), offsetY: CGFloat(0), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let bui_global_carousel_single_slide_container_default = BoxShadow(offsetX: CGFloat(0), offsetY: CGFloat(0), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let bui_global_carousel_multiple_slide_container_default = BoxShadow(offsetX: CGFloat(0), offsetY: CGFloat(0), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let shadow_0 = BoxShadow(offsetX: CGFloat(0), offsetY: CGFloat(0), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let shadow_01 = BoxShadow(offsetX: CGFloat(2), offsetY: CGFloat(-2), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let shadow_02 = BoxShadow(offsetX: CGFloat(-2), offsetY: CGFloat(-2), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let shadow_03 = BoxShadow(offsetX: CGFloat(-2), offsetY: CGFloat(2), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let shadow_04 = BoxShadow(offsetX: CGFloat(2), offsetY: CGFloat(2), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let shadow_05 = BoxShadow(offsetX: CGFloat(4), offsetY: CGFloat(0), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let shadow_06 = BoxShadow(offsetX: CGFloat(0), offsetY: CGFloat(-4), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let shadow_07 = BoxShadow(offsetX: CGFloat(-4), offsetY: CGFloat(0), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
  public static let shadow_08 = BoxShadow(offsetX: CGFloat(0), offsetY: CGFloat(4), blurRadius: CGFloat(8), spread: CGFloat(0), color: UIColor(red: 0.19215686274509805, green: 0.19215686274509805, blue: 0.20784313725490197, alpha: 0.12), type: "dropShadow")
}