// Generated by Style Dictionary on 2025-03-14T15:46:36.244Z
import UIKit

public struct BorderStyle {
  let color: UIColor
  let borderWidth: CGFloat
}

public struct StyleDictionaryBorders {
  public static let bui_global_button_container_border_primary_hover = BorderStyle(
    color: UIColor(red: 0.451, green: 0.157, blue: 0.012, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_button_container_border_secondary_enabled = BorderStyle(
    color: UIColor(red: 0.953, green: 0.451, blue: 0.125, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_button_container_border_secondary_disabled = BorderStyle(
    color: UIColor(red: 0.773, green: 0.773, blue: 0.788, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_button_container_border_secondary_hover = BorderStyle(
    color: UIColor(red: 0.820, green: 0.286, blue: 0.020, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_datepicker_field_border_enabled = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_datepicker_field_border_focus = BorderStyle(
    color: UIColor(red: 0.502, green: 0.353, blue: 0.863, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_datepicker_field_border_danger = BorderStyle(
    color: UIColor(red: 0.910, green: 0.008, blue: 0.008, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_datepicker_field_border_active = BorderStyle(
    color: UIColor(red: 0.502, green: 0.353, blue: 0.863, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_datepicker_field_border_disabled = BorderStyle(
    color: UIColor(red: 0.773, green: 0.773, blue: 0.788, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_datepicker_field_border_completed = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_list_header_border_bottom = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_list_item_avatar_border_hover = BorderStyle(
    color: UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1).toUIColor,
    borderWidth: 2.toCGFloat
  )
  public static let bui_global_list_item_border_bottom = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_list_container_border_default = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_sidebar_container_border_right_default = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_sidebar_container_border_top_default = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_tab_border_bottom_enabled = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_tab_border_bottom_disabled = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_tab_border_bottom_hover = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_tab_border_top_active = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_tab_border_right_active = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_tab_border_left_active = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_link_border_bottom_hover = BorderStyle(
    color: UIColor(red: 0.357, green: 0.251, blue: 0.612, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_avatar_badge_container_border_default = BorderStyle(
    color: UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1).toUIColor,
    borderWidth: 2.toCGFloat
  )
  public static let bui_global_card_container_border_default = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_field_border_enabled = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_field_border_focus = BorderStyle(
    color: UIColor(red: 0.502, green: 0.353, blue: 0.863, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_field_border_success = BorderStyle(
    color: UIColor(red: 0.067, green: 0.584, blue: 0.243, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_field_border_danger = BorderStyle(
    color: UIColor(red: 0.910, green: 0.008, blue: 0.008, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_field_border_active = BorderStyle(
    color: UIColor(red: 0.502, green: 0.353, blue: 0.863, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_field_border_disabled = BorderStyle(
    color: UIColor(red: 0.773, green: 0.773, blue: 0.788, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_field_border_completed = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_area_border_focus = BorderStyle(
    color: UIColor(red: 0.502, green: 0.353, blue: 0.863, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_area_border_enabled = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_area_border_success = BorderStyle(
    color: UIColor(red: 0.067, green: 0.584, blue: 0.243, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_area_border_danger = BorderStyle(
    color: UIColor(red: 0.910, green: 0.008, blue: 0.008, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_area_border_active = BorderStyle(
    color: UIColor(red: 0.502, green: 0.353, blue: 0.863, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_area_border_disabled = BorderStyle(
    color: UIColor(red: 0.773, green: 0.773, blue: 0.788, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_text_area_border_completed = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_checkbox_input_border_unchecked_disabled = BorderStyle(
    color: UIColor(red: 0.773, green: 0.773, blue: 0.788, alpha: 1).toUIColor,
    borderWidth: 2.toCGFloat
  )
  public static let bui_global_checkbox_input_border_unchecked_enabled = BorderStyle(
    color: UIColor(red: 0.659, green: 0.659, blue: 0.678, alpha: 1).toUIColor,
    borderWidth: 2.toCGFloat
  )
  public static let bui_global_checkbox_input_border_unchecked_danger = BorderStyle(
    color: UIColor(red: 0.910, green: 0.008, blue: 0.008, alpha: 1).toUIColor,
    borderWidth: 2.toCGFloat
  )
  public static let bui_global_chip_container_border_enabled = BorderStyle(
    color: UIColor(red: 0.357, green: 0.251, blue: 0.612, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_chip_container_border_disabled = BorderStyle(
    color: UIColor(red: 0.659, green: 0.659, blue: 0.678, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_radio_button_border_unselected_enabled = BorderStyle(
    color: UIColor(red: 0.659, green: 0.659, blue: 0.678, alpha: 1).toUIColor,
    borderWidth: 2.toCGFloat
  )
  public static let bui_global_radio_button_border_unselected_disabled = BorderStyle(
    color: UIColor(red: 0.773, green: 0.773, blue: 0.788, alpha: 1).toUIColor,
    borderWidth: 2.toCGFloat
  )
  public static let bui_global_radio_button_border_unselected_danger = BorderStyle(
    color: UIColor(red: 0.910, green: 0.008, blue: 0.008, alpha: 1).toUIColor,
    borderWidth: 2.toCGFloat
  )
  public static let bui_global_dropdown_icon_border_left_error = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_dropdown_border_enabled = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_dropdown_border_focus = BorderStyle(
    color: UIColor(red: 0.502, green: 0.353, blue: 0.863, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_dropdown_border_selected = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_dropdown_border_danger = BorderStyle(
    color: UIColor(red: 0.910, green: 0.008, blue: 0.008, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_dropdown_border_disabled = BorderStyle(
    color: UIColor(red: 0.773, green: 0.773, blue: 0.788, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_toast_border_left_info = BorderStyle(
    color: UIColor(red: 0.455, green: 0.322, blue: 0.784, alpha: 1).toUIColor,
    borderWidth: 8.toCGFloat
  )
  public static let bui_global_toast_border_left_error = BorderStyle(
    color: UIColor(red: 0.910, green: 0.008, blue: 0.008, alpha: 1).toUIColor,
    borderWidth: 8.toCGFloat
  )
  public static let bui_global_toast_border_left_warning = BorderStyle(
    color: UIColor(red: 0.898, green: 0.706, blue: 0.020, alpha: 1).toUIColor,
    borderWidth: 8.toCGFloat
  )
  public static let bui_global_toast_border_left_success = BorderStyle(
    color: UIColor(red: 0.086, green: 0.749, blue: 0.310, alpha: 1).toUIColor,
    borderWidth: 8.toCGFloat
  )
  public static let bui_global_alert_container_border_info = BorderStyle(
    color: UIColor(red: 0.455, green: 0.322, blue: 0.784, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_alert_container_border_error = BorderStyle(
    color: UIColor(red: 0.910, green: 0.008, blue: 0.008, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_alert_container_border_warning = BorderStyle(
    color: UIColor(red: 0.898, green: 0.706, blue: 0.020, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_alert_container_border_success = BorderStyle(
    color: UIColor(red: 0.086, green: 0.749, blue: 0.310, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_app_navigation_bar_container_border_default = BorderStyle(
    color: UIColor(red: 0.867, green: 0.867, blue: 0.875, alpha: 1).toUIColor,
    borderWidth: 1.toCGFloat
  )
  public static let bui_global_button_container_border_radius = 9999
  public static let bui_global_datepicker_dayselector_container_border_radius = 999999
  public static let bui_global_datepicker_monthselector_container_border_radius = 999999
  public static let bui_global_datepicker_yearselector_container_border_radius = 999999
  public static let bui_global_datepicker_calendar_container_border_radius = 16
  public static let bui_global_datepicker_field_border_radius = 8
  public static let bui_global_dialog_container_border_radius = 16
  public static let bui_global_tooltip_container_border_radius = 8
  public static let bui_global_switch_container_border_radius = 999999
  public static let bui_global_switch_dot_border_radius = 999999
  public static let bui_global_list_border_radius = 16
  public static let bui_global_sidebar_item_border_radius = 16
  public static let bui_global_tab_container_border_radius = 8
  public static let bui_global_pagination_page_selector_container_border_radius = 8
  public static let bui_global_avatar_container_border_radius = 999999
  public static let bui_global_card_container_border_radius = 16
  public static let bui_global_text_field_border_radius = 8
  public static let bui_global_text_area_border_radius = 8
  public static let bui_global_checkbox_input_border_radius = 4
  public static let bui_global_chip_container_border_radius = 999999
  public static let bui_global_dropdown_border_radius = 8
  public static let bui_global_badge_container_border_radius = 999999
  public static let bui_global_toast_container_border_radius = 8
  public static let bui_global_alert_container_border_radius = 8
  public static let bui_global_carousel_single_slide_control_active_border_radius = 999999
  public static let bui_global_carousel_single_slide_control_inactive_border_radius = 999999
  public static let bui_global_carousel_single_slide_border_radius = 8
  public static let bui_global_carousel_multiple_slide_border_radius = 8
  public static let bui_global_carousel_arrow_control_border_radius = 8
  public static let bui_app_navigation_bar_floating_action_button_container_border_radius = 999999
  public static let bui_app_navigation_bar_container_border_radius = 8
  public static let border_radius_01 = 4
  public static let border_radius_02 = 8
  public static let border_radius_03 = 16
  public static let border_radius_04 = 24
  public static let border_radius_05 = 32
  public static let border_radius_06 = 40
}